[build]
  base = "frontend/user-console"
  command = "CI=false npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "16"
  NPM_VERSION = "8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200